//Config
export const INITIALIZE_CONFIG = "INITIALIZE_CONFIG";
export const SET_SHOW_LEGAL_MOVES = "SET_SHOW_LEGAL_MOVES";
export const SET_FLIP = "SET_FLIP";
export const SET_TIME_PER_PLAY = "SET_TIME_PER_PLAY";
export const SET_IS_LOADING = "SET_IS_LOADING";

export const INITIALIZE_BOARD = "INITIALIZE_BOARD";
export const SET_SQUARE_SELECTED = "SET_SQUARE_SELECTED";
export const SET_PIECE_MOVED = "SET_PIECE_MOVED";
export const SWITCH_PLAYER = "SWITCH_PLAYER";
export const SET_DATA_FINISHED = "SET_DATA_FINISHED";
export const SET_OFFER_A_DRAW = "SET_OFFER_A_DRAW";
export const SET_ASK_FOR_RESIGN = "SET_ASK_FOR_RESIGN";
export const SET_PAWN_PROMOTION_POSITION = "SET_PAWN_PROMOTION_POSITION";
