//Config
export const INITIALIZE_CONFIG = "INITIALIZE_CONFIG";
export const SET_SHOW_LEGAL_MOVES = "SET_SHOW_LEGAL_MOVES";
export const SET_TIME_PER_PLAY = "SET_TIME_PER_PLAY";

export const INITIALIZE_BOARD = "INITIALIZE_BOARD";
export const SET_SQUARE_SELECTED = "SET_SQUARE_SELECTED";
export const SWITCH_PLAYER = "SWITCH_PLAYER";
export const SET_WINNER = "SET_WINNER";
export const SET_STATUS = "SET_STATUS";
export const SET_MODAL_VISIBLE = "SET_MODAL_VISIBLE";
