export const SET_SELECTED = "SET_SELECTED";
export const SET_SHOW_LEGAL_MOVES = "SET_SHOW_LEGAL_MOVES";
export const SET_TIME_PER_PLAY = "SET_TIME_PER_PLAY";
export const SWITCH_PLAYER = "SWITCH_PLAYER";
